# Generated by Django 4.0.4 on 2022-06-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(help_text='375_________', max_length=13, verbose_name='Тел.')),
                ('salary', models.IntegerField(verbose_name='Оклад')),
                ('addres', models.CharField(max_length=50, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
                'db_table': 'Trainers',
            },
        ),
        migrations.CreateModel(
            name='Trainers_spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100, verbose_name='Примечание')),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers', verbose_name='Номер сотрудника')),
                ('service_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'db_table': 'Services_spec',
            },
        ),
    ]
