# Generated by Django 4.0.4 on 2022-06-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='addres',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
