# Generated by Django 4.0.4 on 2022-06-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
