# Generated by Django 4.0.4 on 2022-06-04 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название абонемента')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('number_of_visits', models.IntegerField(verbose_name='Количество посещений')),
                ('number_of_days', models.IntegerField(verbose_name='Количество дней')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'db_table': 'Card',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название услуги')),
                ('image', models.ImageField(upload_to='')),
                ('about', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Card_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('finish_date', models.DateField(verbose_name='Дата окончания')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.card', verbose_name='абонемент клиента')),
                ('client_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Код клиента')),
            ],
            options={
                'verbose_name': 'Продажа абонемента',
                'verbose_name_plural': 'Продажа абонементов',
                'db_table': 'Card_sale',
            },
        ),
    ]
