# Generated by Django 4.0.4 on 2022-06-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutVideo',
            fields=[
                ('workout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workout.workout')),
                ('url', models.URLField()),
            ],
            bases=('workout.workout',),
        ),
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='video',
            field=models.ImageField(null=True, upload_to='static/movie/'),
        ),
    ]
