# Generated by Django 4.0.4 on 2022-06-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('main', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Начало тренировки')),
                ('time_finish', models.TimeField(verbose_name='Конец тренировки')),
                ('note', models.CharField(max_length=100, verbose_name='Примечание')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Услуга')),
                ('sportroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sportroom', verbose_name='Помещение')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers', verbose_name='Персонал')),
            ],
            options={
                'verbose_name': 'Расписание',
                'db_table': 'Shedule',
            },
        ),
        migrations.CreateModel(
            name='Visitation_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.card_sale', verbose_name='Номер карты')),
                ('namber_shedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.shedule', verbose_name='№ по расписанию')),
            ],
            options={
                'verbose_name': 'Запись о посещении',
                'verbose_name_plural': 'Записи о посещениях',
                'db_table': 'Visitation_record',
            },
        ),
    ]
