# Generated by Django 4.0.4 on 2022-06-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Контакты')),
                ('name', models.CharField(max_length=50, verbose_name='Название клуба')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.IntegerField(verbose_name='Дом')),
                ('phone', models.CharField(help_text='375_________', max_length=13, verbose_name='Тел.')),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.TextField(verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Правила клуба')),
                ('rules', models.TextField()),
            ],
            options={
                'verbose_name': 'Правила',
                'verbose_name_plural': 'Правила',
                'db_table': 'Rules',
            },
        ),
    ]
